# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Misc\NeuralNet.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NeuralNet(object):
    def setupUi(self, NeuralNet):
        NeuralNet.setObjectName(_fromUtf8("NeuralNet"))
        NeuralNet.setEnabled(True)
        NeuralNet.resize(445, 430)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NeuralNet.sizePolicy().hasHeightForWidth())
        NeuralNet.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(NeuralNet)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.openTrainingButton = QtGui.QPushButton(NeuralNet)
        self.openTrainingButton.setObjectName(_fromUtf8("openTrainingButton"))
        self.horizontalLayout.addWidget(self.openTrainingButton)
        self.openTestButton = QtGui.QPushButton(NeuralNet)
        self.openTestButton.setObjectName(_fromUtf8("openTestButton"))
        self.horizontalLayout.addWidget(self.openTestButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(NeuralNet)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.nrInputsSpinBox = QtGui.QSpinBox(NeuralNet)
        self.nrInputsSpinBox.setMinimum(1)
        self.nrInputsSpinBox.setObjectName(_fromUtf8("nrInputsSpinBox"))
        self.horizontalLayout.addWidget(self.nrInputsSpinBox)
        self.label_2 = QtGui.QLabel(NeuralNet)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.nroutputsLabel = QtGui.QLabel(NeuralNet)
        self.nroutputsLabel.setObjectName(_fromUtf8("nroutputsLabel"))
        self.horizontalLayout.addWidget(self.nroutputsLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(NeuralNet)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.layersSpinBox = QtGui.QSpinBox(NeuralNet)
        self.layersSpinBox.setMinimum(1)
        self.layersSpinBox.setMaximum(100000)
        self.layersSpinBox.setObjectName(_fromUtf8("layersSpinBox"))
        self.horizontalLayout_3.addWidget(self.layersSpinBox)
        self.label_4 = QtGui.QLabel(NeuralNet)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.neuronsSpinBox = QtGui.QSpinBox(NeuralNet)
        self.neuronsSpinBox.setMinimum(1)
        self.neuronsSpinBox.setMaximum(100000)
        self.neuronsSpinBox.setObjectName(_fromUtf8("neuronsSpinBox"))
        self.horizontalLayout_3.addWidget(self.neuronsSpinBox)
        self.label_5 = QtGui.QLabel(NeuralNet)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.maxIterSpinBox = QtGui.QSpinBox(NeuralNet)
        self.maxIterSpinBox.setMinimum(1)
        self.maxIterSpinBox.setMaximum(1000000000)
        self.maxIterSpinBox.setSingleStep(10000)
        self.maxIterSpinBox.setProperty("value", 100000)
        self.maxIterSpinBox.setObjectName(_fromUtf8("maxIterSpinBox"))
        self.horizontalLayout_3.addWidget(self.maxIterSpinBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_9 = QtGui.QLabel(NeuralNet)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.connectionRateSpinBox = QtGui.QDoubleSpinBox(NeuralNet)
        self.connectionRateSpinBox.setMinimum(0.01)
        self.connectionRateSpinBox.setMaximum(1.0)
        self.connectionRateSpinBox.setSingleStep(0.01)
        self.connectionRateSpinBox.setProperty("value", 1.0)
        self.connectionRateSpinBox.setObjectName(_fromUtf8("connectionRateSpinBox"))
        self.horizontalLayout_4.addWidget(self.connectionRateSpinBox)
        self.label_10 = QtGui.QLabel(NeuralNet)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        self.learningRateSpinBox = QtGui.QDoubleSpinBox(NeuralNet)
        self.learningRateSpinBox.setMinimum(0.01)
        self.learningRateSpinBox.setMaximum(1.0)
        self.learningRateSpinBox.setSingleStep(0.01)
        self.learningRateSpinBox.setProperty("value", 1.0)
        self.learningRateSpinBox.setObjectName(_fromUtf8("learningRateSpinBox"))
        self.horizontalLayout_4.addWidget(self.learningRateSpinBox)
        self.label_6 = QtGui.QLabel(NeuralNet)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.desiredErrorSpinBox = QtGui.QDoubleSpinBox(NeuralNet)
        self.desiredErrorSpinBox.setDecimals(5)
        self.desiredErrorSpinBox.setMaximum(10.0)
        self.desiredErrorSpinBox.setSingleStep(0.0001)
        self.desiredErrorSpinBox.setProperty("value", 0.0)
        self.desiredErrorSpinBox.setObjectName(_fromUtf8("desiredErrorSpinBox"))
        self.horizontalLayout_4.addWidget(self.desiredErrorSpinBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.trainingDataTable = QtGui.QTableWidget(NeuralNet)
        self.trainingDataTable.setObjectName(_fromUtf8("trainingDataTable"))
        self.trainingDataTable.setColumnCount(2)
        self.trainingDataTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.trainingDataTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.trainingDataTable.setHorizontalHeaderItem(1, item)
        self.trainingDataTable.horizontalHeader().setDefaultSectionSize(70)
        self.trainingDataTable.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout.addWidget(self.trainingDataTable)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton = QtGui.QPushButton(NeuralNet)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtGui.QPushButton(NeuralNet)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(NeuralNet)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_2 = QtGui.QPushButton(NeuralNet)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.testDataTable = QtGui.QTableWidget(NeuralNet)
        self.testDataTable.setObjectName(_fromUtf8("testDataTable"))
        self.testDataTable.setColumnCount(2)
        self.testDataTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.testDataTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.testDataTable.setHorizontalHeaderItem(1, item)
        self.testDataTable.horizontalHeader().setDefaultSectionSize(70)
        self.testDataTable.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout.addWidget(self.testDataTable)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(NeuralNet)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.minResolutionEdit = QtGui.QLineEdit(NeuralNet)
        self.minResolutionEdit.setEnabled(True)
        self.minResolutionEdit.setReadOnly(True)
        self.minResolutionEdit.setObjectName(_fromUtf8("minResolutionEdit"))
        self.horizontalLayout_5.addWidget(self.minResolutionEdit)
        self.label_8 = QtGui.QLabel(NeuralNet)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.desiredResolutionEdit = QtGui.QLineEdit(NeuralNet)
        self.desiredResolutionEdit.setObjectName(_fromUtf8("desiredResolutionEdit"))
        self.horizontalLayout_5.addWidget(self.desiredResolutionEdit)
        self.matchButton = QtGui.QPushButton(NeuralNet)
        self.matchButton.setObjectName(_fromUtf8("matchButton"))
        self.horizontalLayout_5.addWidget(self.matchButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(NeuralNet)
        QtCore.QObject.connect(self.openTrainingButton, QtCore.SIGNAL(_fromUtf8("clicked()")), NeuralNet.FileOpenTraining)
        QtCore.QObject.connect(self.nrInputsSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), NeuralNet.NrInputsChanged)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), NeuralNet.Train)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), NeuralNet.Test)
        QtCore.QObject.connect(self.matchButton, QtCore.SIGNAL(_fromUtf8("clicked()")), NeuralNet.Match)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), NeuralNet.Save)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), NeuralNet.Load)
        QtCore.QObject.connect(self.openTestButton, QtCore.SIGNAL(_fromUtf8("clicked()")), NeuralNet.FileOpenTest)
        QtCore.QMetaObject.connectSlotsByName(NeuralNet)

    def retranslateUi(self, NeuralNet):
        NeuralNet.setWindowTitle(_translate("NeuralNet", "NeuralNet", None))
        NeuralNet.setTitle(_translate("NeuralNet", "NeuralNet Calculations", None))
        self.openTrainingButton.setText(_translate("NeuralNet", "Open Training", None))
        self.openTestButton.setText(_translate("NeuralNet", "Open Test", None))
        self.label.setText(_translate("NeuralNet", "Inputs:", None))
        self.label_2.setText(_translate("NeuralNet", "Outputs:", None))
        self.nroutputsLabel.setText(_translate("NeuralNet", "0", None))
        self.label_3.setText(_translate("NeuralNet", "Layers:", None))
        self.label_4.setText(_translate("NeuralNet", "Neurons / layer:", None))
        self.label_5.setText(_translate("NeuralNet", "Max iterations:", None))
        self.label_9.setText(_translate("NeuralNet", "Connection rate:", None))
        self.label_10.setText(_translate("NeuralNet", "Learning rate:", None))
        self.label_6.setText(_translate("NeuralNet", "Desired error:", None))
        item = self.trainingDataTable.horizontalHeaderItem(0)
        item.setText(_translate("NeuralNet", "New Column", None))
        item = self.trainingDataTable.horizontalHeaderItem(1)
        item.setText(_translate("NeuralNet", "New Column", None))
        self.pushButton.setText(_translate("NeuralNet", "Train", None))
        self.pushButton_3.setText(_translate("NeuralNet", "Save", None))
        self.pushButton_4.setText(_translate("NeuralNet", "Load", None))
        self.pushButton_2.setText(_translate("NeuralNet", "Test", None))
        item = self.testDataTable.horizontalHeaderItem(0)
        item.setText(_translate("NeuralNet", "New Column", None))
        item = self.testDataTable.horizontalHeaderItem(1)
        item.setText(_translate("NeuralNet", "New Column", None))
        self.label_7.setText(_translate("NeuralNet", "Min resolution:", None))
        self.minResolutionEdit.setText(_translate("NeuralNet", "0.0001", None))
        self.label_8.setText(_translate("NeuralNet", "Desired resolution:", None))
        self.matchButton.setText(_translate("NeuralNet", "Match", None))

