# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScanmanGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1316, 679)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.dataset_spin = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataset_spin.sizePolicy().hasHeightForWidth())
        self.dataset_spin.setSizePolicy(sizePolicy)
        self.dataset_spin.setMaximum(0)
        self.dataset_spin.setObjectName(_fromUtf8("dataset_spin"))
        self.gridLayout_2.addWidget(self.dataset_spin, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.nrdatasets_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nrdatasets_label.sizePolicy().hasHeightForWidth())
        self.nrdatasets_label.setSizePolicy(sizePolicy)
        self.nrdatasets_label.setObjectName(_fromUtf8("nrdatasets_label"))
        self.gridLayout_2.addWidget(self.nrdatasets_label, 0, 1, 1, 1)
        self.cursource_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cursource_label.sizePolicy().hasHeightForWidth())
        self.cursource_label.setSizePolicy(sizePolicy)
        self.cursource_label.setObjectName(_fromUtf8("cursource_label"))
        self.gridLayout_2.addWidget(self.cursource_label, 0, 6, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 5, 1, 1)
        self.clear_btn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_btn.sizePolicy().hasHeightForWidth())
        self.clear_btn.setSizePolicy(sizePolicy)
        self.clear_btn.setMinimumSize(QtCore.QSize(20, 0))
        self.clear_btn.setObjectName(_fromUtf8("clear_btn"))
        self.gridLayout_2.addWidget(self.clear_btn, 0, 7, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.source_tab = QtGui.QWidget()
        self.source_tab.setObjectName(_fromUtf8("source_tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.source_tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.sourceLayout = QtGui.QVBoxLayout()
        self.sourceLayout.setObjectName(_fromUtf8("sourceLayout"))
        self.sourceComboBox = QtGui.QComboBox(self.source_tab)
        self.sourceComboBox.setObjectName(_fromUtf8("sourceComboBox"))
        self.sourceLayout.addWidget(self.sourceComboBox)
        self.sourceGroupBox = QtGui.QGroupBox(self.source_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourceGroupBox.sizePolicy().hasHeightForWidth())
        self.sourceGroupBox.setSizePolicy(sizePolicy)
        self.sourceGroupBox.setTitle(_fromUtf8(""))
        self.sourceGroupBox.setObjectName(_fromUtf8("sourceGroupBox"))
        self.sourceLayout.addWidget(self.sourceGroupBox)
        self.verticalLayout_4.addLayout(self.sourceLayout)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.selectall_check = QtGui.QCheckBox(self.source_tab)
        self.selectall_check.setObjectName(_fromUtf8("selectall_check"))
        self.horizontalLayout_9.addWidget(self.selectall_check)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.manparam_btn = QtGui.QPushButton(self.source_tab)
        self.manparam_btn.setObjectName(_fromUtf8("manparam_btn"))
        self.horizontalLayout_9.addWidget(self.manparam_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.prm_table = QtGui.QTableWidget(self.source_tab)
        self.prm_table.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged)
        self.prm_table.setTabKeyNavigation(False)
        self.prm_table.setProperty("showDropIndicator", False)
        self.prm_table.setCornerButtonEnabled(True)
        self.prm_table.setObjectName(_fromUtf8("prm_table"))
        self.prm_table.setColumnCount(3)
        self.prm_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.prm_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.prm_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.prm_table.setHorizontalHeaderItem(2, item)
        self.prm_table.horizontalHeader().setDefaultSectionSize(120)
        self.prm_table.verticalHeader().setDefaultSectionSize(19)
        self.verticalLayout_4.addWidget(self.prm_table)
        self.postprocessGroupBox = QtGui.QGroupBox(self.source_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postprocessGroupBox.sizePolicy().hasHeightForWidth())
        self.postprocessGroupBox.setSizePolicy(sizePolicy)
        self.postprocessGroupBox.setCheckable(True)
        self.postprocessGroupBox.setChecked(False)
        self.postprocessGroupBox.setObjectName(_fromUtf8("postprocessGroupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.postprocessGroupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(self.postprocessGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.normalise_combo = QtGui.QComboBox(self.postprocessGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalise_combo.sizePolicy().hasHeightForWidth())
        self.normalise_combo.setSizePolicy(sizePolicy)
        self.normalise_combo.setMinimumSize(QtCore.QSize(40, 0))
        self.normalise_combo.setObjectName(_fromUtf8("normalise_combo"))
        self.normalise_combo.addItem(_fromUtf8(""))
        self.normalise_combo.setItemText(0, _fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.normalise_combo)
        self.label_10 = QtGui.QLabel(self.postprocessGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.sum_combo = QtGui.QComboBox(self.postprocessGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sum_combo.sizePolicy().hasHeightForWidth())
        self.sum_combo.setSizePolicy(sizePolicy)
        self.sum_combo.setMinimumSize(QtCore.QSize(50, 0))
        self.sum_combo.setObjectName(_fromUtf8("sum_combo"))
        self.sum_combo.addItem(_fromUtf8(""))
        self.sum_combo.setItemText(0, _fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.sum_combo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_11 = QtGui.QLabel(self.postprocessGroupBox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_11.addWidget(self.label_11)
        self.scale_edit = QtGui.QLineEdit(self.postprocessGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scale_edit.sizePolicy().hasHeightForWidth())
        self.scale_edit.setSizePolicy(sizePolicy)
        self.scale_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scale_edit.setObjectName(_fromUtf8("scale_edit"))
        self.horizontalLayout_11.addWidget(self.scale_edit)
        self.label_13 = QtGui.QLabel(self.postprocessGroupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_11.addWidget(self.label_13)
        self.stthoffset_edit = QtGui.QLineEdit(self.postprocessGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stthoffset_edit.sizePolicy().hasHeightForWidth())
        self.stthoffset_edit.setSizePolicy(sizePolicy)
        self.stthoffset_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stthoffset_edit.setObjectName(_fromUtf8("stthoffset_edit"))
        self.horizontalLayout_11.addWidget(self.stthoffset_edit)
        self.justsum_check = QtGui.QCheckBox(self.postprocessGroupBox)
        self.justsum_check.setObjectName(_fromUtf8("justsum_check"))
        self.horizontalLayout_11.addWidget(self.justsum_check)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.postprocessapplyButton = QtGui.QPushButton(self.postprocessGroupBox)
        self.postprocessapplyButton.setObjectName(_fromUtf8("postprocessapplyButton"))
        self.horizontalLayout_12.addWidget(self.postprocessapplyButton)
        spacerItem2 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.verticalLayout_4.addWidget(self.postprocessGroupBox)
        self.tabWidget.addTab(self.source_tab, _fromUtf8(""))
        self.fit_tab = QtGui.QWidget()
        self.fit_tab.setObjectName(_fromUtf8("fit_tab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.fit_tab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.fitLayout = QtGui.QVBoxLayout()
        self.fitLayout.setObjectName(_fromUtf8("fitLayout"))
        self.fitComboBox = QtGui.QComboBox(self.fit_tab)
        self.fitComboBox.setObjectName(_fromUtf8("fitComboBox"))
        self.fitLayout.addWidget(self.fitComboBox)
        self.fitGroupBox = QtGui.QGroupBox(self.fit_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitGroupBox.sizePolicy().hasHeightForWidth())
        self.fitGroupBox.setSizePolicy(sizePolicy)
        self.fitGroupBox.setObjectName(_fromUtf8("fitGroupBox"))
        self.fitLayout.addWidget(self.fitGroupBox)
        self.verticalLayout_6.addLayout(self.fitLayout)
        self.fit_btn = QtGui.QPushButton(self.fit_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fit_btn.sizePolicy().hasHeightForWidth())
        self.fit_btn.setSizePolicy(sizePolicy)
        self.fit_btn.setObjectName(_fromUtf8("fit_btn"))
        self.verticalLayout_6.addWidget(self.fit_btn)
        self.tabWidget.addTab(self.fit_tab, _fromUtf8(""))
        self.output_tab = QtGui.QWidget()
        self.output_tab.setObjectName(_fromUtf8("output_tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.output_tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.outputLayout = QtGui.QVBoxLayout()
        self.outputLayout.setObjectName(_fromUtf8("outputLayout"))
        self.outputComboBox = QtGui.QComboBox(self.output_tab)
        self.outputComboBox.setObjectName(_fromUtf8("outputComboBox"))
        self.outputLayout.addWidget(self.outputComboBox)
        self.outputGroupBox = QtGui.QGroupBox(self.output_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputGroupBox.sizePolicy().hasHeightForWidth())
        self.outputGroupBox.setSizePolicy(sizePolicy)
        self.outputGroupBox.setObjectName(_fromUtf8("outputGroupBox"))
        self.outputLayout.addWidget(self.outputGroupBox)
        self.verticalLayout.addLayout(self.outputLayout)
        self.tabWidget.addTab(self.output_tab, _fromUtf8(""))
        self.misc_tab = QtGui.QWidget()
        self.misc_tab.setObjectName(_fromUtf8("misc_tab"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.misc_tab)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.miscLayout = QtGui.QVBoxLayout()
        self.miscLayout.setObjectName(_fromUtf8("miscLayout"))
        self.miscComboBox = QtGui.QComboBox(self.misc_tab)
        self.miscComboBox.setObjectName(_fromUtf8("miscComboBox"))
        self.miscLayout.addWidget(self.miscComboBox)
        self.miscGroupBox = QtGui.QGroupBox(self.misc_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.miscGroupBox.sizePolicy().hasHeightForWidth())
        self.miscGroupBox.setSizePolicy(sizePolicy)
        self.miscGroupBox.setObjectName(_fromUtf8("miscGroupBox"))
        self.miscLayout.addWidget(self.miscGroupBox)
        self.verticalLayout_10.addLayout(self.miscLayout)
        self.tabWidget.addTab(self.misc_tab, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(1, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1316, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_4 = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_4.sizePolicy().hasHeightForWidth())
        self.dockWidget_4.setSizePolicy(sizePolicy)
        self.dockWidget_4.setMinimumSize(QtCore.QSize(300, 322))
        self.dockWidget_4.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_4.setObjectName(_fromUtf8("dockWidget_4"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents_4.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_4.setSizePolicy(sizePolicy)
        self.dockWidgetContents_4.setMinimumSize(QtCore.QSize(50, 300))
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.filename_edit = QtGui.QLineEdit(self.dockWidgetContents_4)
        self.filename_edit.setEnabled(True)
        self.filename_edit.setAutoFillBackground(True)
        self.filename_edit.setFrame(False)
        self.filename_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.filename_edit.setReadOnly(True)
        self.filename_edit.setObjectName(_fromUtf8("filename_edit"))
        self.verticalLayout_5.addWidget(self.filename_edit)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setVerticalSpacing(2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.maskUpper_slider = QtGui.QSlider(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maskUpper_slider.sizePolicy().hasHeightForWidth())
        self.maskUpper_slider.setSizePolicy(sizePolicy)
        self.maskUpper_slider.setProperty("value", 99)
        self.maskUpper_slider.setOrientation(QtCore.Qt.Horizontal)
        self.maskUpper_slider.setObjectName(_fromUtf8("maskUpper_slider"))
        self.gridLayout_4.addWidget(self.maskUpper_slider, 1, 1, 1, 1)
        self.maskUpper_label = QtGui.QLabel(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maskUpper_label.sizePolicy().hasHeightForWidth())
        self.maskUpper_label.setSizePolicy(sizePolicy)
        self.maskUpper_label.setObjectName(_fromUtf8("maskUpper_label"))
        self.gridLayout_4.addWidget(self.maskUpper_label, 1, 0, 1, 1)
        self.maskLower_label = QtGui.QLabel(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maskLower_label.sizePolicy().hasHeightForWidth())
        self.maskLower_label.setSizePolicy(sizePolicy)
        self.maskLower_label.setObjectName(_fromUtf8("maskLower_label"))
        self.gridLayout_4.addWidget(self.maskLower_label, 0, 0, 1, 1)
        self.maskLower_slider = QtGui.QSlider(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maskLower_slider.sizePolicy().hasHeightForWidth())
        self.maskLower_slider.setSizePolicy(sizePolicy)
        self.maskLower_slider.setTracking(True)
        self.maskLower_slider.setOrientation(QtCore.Qt.Horizontal)
        self.maskLower_slider.setInvertedAppearance(False)
        self.maskLower_slider.setInvertedControls(False)
        self.maskLower_slider.setObjectName(_fromUtf8("maskLower_slider"))
        self.gridLayout_4.addWidget(self.maskLower_slider, 0, 1, 1, 1)
        self.maskUpper_edit = QtGui.QLineEdit(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maskUpper_edit.sizePolicy().hasHeightForWidth())
        self.maskUpper_edit.setSizePolicy(sizePolicy)
        self.maskUpper_edit.setMinimumSize(QtCore.QSize(20, 0))
        self.maskUpper_edit.setObjectName(_fromUtf8("maskUpper_edit"))
        self.gridLayout_4.addWidget(self.maskUpper_edit, 1, 2, 1, 1)
        self.maskLower_edit = QtGui.QLineEdit(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maskLower_edit.sizePolicy().hasHeightForWidth())
        self.maskLower_edit.setSizePolicy(sizePolicy)
        self.maskLower_edit.setMinimumSize(QtCore.QSize(20, 0))
        self.maskLower_edit.setObjectName(_fromUtf8("maskLower_edit"))
        self.gridLayout_4.addWidget(self.maskLower_edit, 0, 2, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 10)
        self.gridLayout_4.setColumnStretch(2, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.graph = MatplotlibWidget(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph.sizePolicy().hasHeightForWidth())
        self.graph.setSizePolicy(sizePolicy)
        self.graph.setMinimumSize(QtCore.QSize(0, 0))
        self.graph.setObjectName(_fromUtf8("graph"))
        self.verticalLayout_5.addWidget(self.graph)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setVerticalSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        self.position_radio = QtGui.QRadioButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_radio.sizePolicy().hasHeightForWidth())
        self.position_radio.setSizePolicy(sizePolicy)
        self.position_radio.setObjectName(_fromUtf8("position_radio"))
        self.gridLayout_3.addWidget(self.position_radio, 0, 1, 1, 1)
        self.angle_radio = QtGui.QRadioButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_radio.sizePolicy().hasHeightForWidth())
        self.angle_radio.setSizePolicy(sizePolicy)
        self.angle_radio.setObjectName(_fromUtf8("angle_radio"))
        self.gridLayout_3.addWidget(self.angle_radio, 0, 3, 1, 1)
        self.dspacing_radio = QtGui.QRadioButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dspacing_radio.sizePolicy().hasHeightForWidth())
        self.dspacing_radio.setSizePolicy(sizePolicy)
        self.dspacing_radio.setObjectName(_fromUtf8("dspacing_radio"))
        self.gridLayout_3.addWidget(self.dspacing_radio, 0, 5, 1, 1)
        self.channel_radio = QtGui.QRadioButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel_radio.sizePolicy().hasHeightForWidth())
        self.channel_radio.setSizePolicy(sizePolicy)
        self.channel_radio.setChecked(True)
        self.channel_radio.setObjectName(_fromUtf8("channel_radio"))
        self.gridLayout_3.addWidget(self.channel_radio, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_8 = QtGui.QLabel(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self.wavelength_edit = QtGui.QLineEdit(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wavelength_edit.sizePolicy().hasHeightForWidth())
        self.wavelength_edit.setSizePolicy(sizePolicy)
        self.wavelength_edit.setMinimumSize(QtCore.QSize(5, 0))
        self.wavelength_edit.setReadOnly(False)
        self.wavelength_edit.setObjectName(_fromUtf8("wavelength_edit"))
        self.horizontalLayout_6.addWidget(self.wavelength_edit)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 1, 5, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.stth_edit = QtGui.QLineEdit(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stth_edit.sizePolicy().hasHeightForWidth())
        self.stth_edit.setSizePolicy(sizePolicy)
        self.stth_edit.setEchoMode(QtGui.QLineEdit.Normal)
        self.stth_edit.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.stth_edit.setReadOnly(False)
        self.stth_edit.setObjectName(_fromUtf8("stth_edit"))
        self.horizontalLayout.addWidget(self.stth_edit)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 3, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.detDim_xmin_edit = QtGui.QLineEdit(self.dockWidgetContents_4)
        self.detDim_xmin_edit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detDim_xmin_edit.sizePolicy().hasHeightForWidth())
        self.detDim_xmin_edit.setSizePolicy(sizePolicy)
        self.detDim_xmin_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.detDim_xmin_edit.setReadOnly(False)
        self.detDim_xmin_edit.setObjectName(_fromUtf8("detDim_xmin_edit"))
        self.horizontalLayout_3.addWidget(self.detDim_xmin_edit)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.sam2det_edit = QtGui.QLineEdit(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sam2det_edit.sizePolicy().hasHeightForWidth())
        self.sam2det_edit.setSizePolicy(sizePolicy)
        self.sam2det_edit.setMinimumSize(QtCore.QSize(5, 0))
        self.sam2det_edit.setReadOnly(False)
        self.sam2det_edit.setObjectName(_fromUtf8("sam2det_edit"))
        self.horizontalLayout_5.addWidget(self.sam2det_edit)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 4, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.detDim_xmax_edit = QtGui.QLineEdit(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detDim_xmax_edit.sizePolicy().hasHeightForWidth())
        self.detDim_xmax_edit.setSizePolicy(sizePolicy)
        self.detDim_xmax_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.detDim_xmax_edit.setReadOnly(False)
        self.detDim_xmax_edit.setObjectName(_fromUtf8("detDim_xmax_edit"))
        self.horizontalLayout_4.addWidget(self.detDim_xmax_edit)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.slideminLabel = QtGui.QLabel(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slideminLabel.sizePolicy().hasHeightForWidth())
        self.slideminLabel.setSizePolicy(sizePolicy)
        self.slideminLabel.setObjectName(_fromUtf8("slideminLabel"))
        self.gridLayout.addWidget(self.slideminLabel, 0, 0, 1, 1)
        self.minSlider = QtGui.QSlider(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minSlider.sizePolicy().hasHeightForWidth())
        self.minSlider.setSizePolicy(sizePolicy)
        self.minSlider.setTracking(True)
        self.minSlider.setOrientation(QtCore.Qt.Horizontal)
        self.minSlider.setInvertedAppearance(False)
        self.minSlider.setInvertedControls(False)
        self.minSlider.setObjectName(_fromUtf8("minSlider"))
        self.gridLayout.addWidget(self.minSlider, 0, 1, 1, 1)
        self.slidemaxLabel = QtGui.QLabel(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slidemaxLabel.sizePolicy().hasHeightForWidth())
        self.slidemaxLabel.setSizePolicy(sizePolicy)
        self.slidemaxLabel.setObjectName(_fromUtf8("slidemaxLabel"))
        self.gridLayout.addWidget(self.slidemaxLabel, 1, 0, 1, 1)
        self.maxvalLabel = QtGui.QLabel(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxvalLabel.sizePolicy().hasHeightForWidth())
        self.maxvalLabel.setSizePolicy(sizePolicy)
        self.maxvalLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.maxvalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxvalLabel.setObjectName(_fromUtf8("maxvalLabel"))
        self.gridLayout.addWidget(self.maxvalLabel, 1, 2, 1, 1)
        self.minvalLabel = QtGui.QLabel(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minvalLabel.sizePolicy().hasHeightForWidth())
        self.minvalLabel.setSizePolicy(sizePolicy)
        self.minvalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minvalLabel.setObjectName(_fromUtf8("minvalLabel"))
        self.gridLayout.addWidget(self.minvalLabel, 0, 2, 1, 1)
        self.maxSlider = QtGui.QSlider(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxSlider.sizePolicy().hasHeightForWidth())
        self.maxSlider.setSizePolicy(sizePolicy)
        self.maxSlider.setProperty("value", 0)
        self.maxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider.setObjectName(_fromUtf8("maxSlider"))
        self.gridLayout.addWidget(self.maxSlider, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 10)
        self.gridLayout.setColumnStretch(2, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.diffgraph = MatplotlibWidget(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diffgraph.sizePolicy().hasHeightForWidth())
        self.diffgraph.setSizePolicy(sizePolicy)
        self.diffgraph.setMinimumSize(QtCore.QSize(0, 0))
        self.diffgraph.setObjectName(_fromUtf8("diffgraph"))
        self.verticalLayout_5.addWidget(self.diffgraph)
        self.verticalLayout_5.setStretch(2, 10)
        self.verticalLayout_5.setStretch(5, 2)
        self.dockWidget_4.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_4)
        self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_2.setEnabled(True)
        self.dockWidget_2.setFloating(False)
        self.dockWidget_2.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.graph_2d = MatplotlibWidget(self.dockWidgetContents_2)
        self.graph_2d.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_2d.sizePolicy().hasHeightForWidth())
        self.graph_2d.setSizePolicy(sizePolicy)
        self.graph_2d.setMinimumSize(QtCore.QSize(0, 0))
        self.graph_2d.setObjectName(_fromUtf8("graph_2d"))
        self.verticalLayout_3.addWidget(self.graph_2d)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.flatfield_check = QtGui.QCheckBox(self.dockWidgetContents_2)
        self.flatfield_check.setChecked(False)
        self.flatfield_check.setObjectName(_fromUtf8("flatfield_check"))
        self.horizontalLayout_7.addWidget(self.flatfield_check)
        self.fffname_edit = QtGui.QLineEdit(self.dockWidgetContents_2)
        self.fffname_edit.setObjectName(_fromUtf8("fffname_edit"))
        self.horizontalLayout_7.addWidget(self.fffname_edit)
        self.ffopen_button = QtGui.QPushButton(self.dockWidgetContents_2)
        self.ffopen_button.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ffopen_button.sizePolicy().hasHeightForWidth())
        self.ffopen_button.setSizePolicy(sizePolicy)
        self.ffopen_button.setMinimumSize(QtCore.QSize(0, 0))
        self.ffopen_button.setObjectName(_fromUtf8("ffopen_button"))
        self.horizontalLayout_7.addWidget(self.ffopen_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.detectorsplit_label = QtGui.QLabel(self.dockWidgetContents_2)
        self.detectorsplit_label.setObjectName(_fromUtf8("detectorsplit_label"))
        self.horizontalLayout_8.addWidget(self.detectorsplit_label)
        self.vsplit_combo = QtGui.QComboBox(self.dockWidgetContents_2)
        self.vsplit_combo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.vsplit_combo.setObjectName(_fromUtf8("vsplit_combo"))
        self.vsplit_combo.addItem(_fromUtf8(""))
        self.vsplit_combo.addItem(_fromUtf8(""))
        self.vsplit_combo.addItem(_fromUtf8(""))
        self.vsplit_combo.addItem(_fromUtf8(""))
        self.vsplit_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.vsplit_combo)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.geometry_check = QtGui.QCheckBox(self.dockWidgetContents_2)
        self.geometry_check.setChecked(False)
        self.geometry_check.setObjectName(_fromUtf8("geometry_check"))
        self.verticalLayout_3.addWidget(self.geometry_check)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.absorption_check = QtGui.QCheckBox(self.dockWidgetContents_2)
        self.absorption_check.setObjectName(_fromUtf8("absorption_check"))
        self.horizontalLayout_13.addWidget(self.absorption_check)
        self.abs_cor_btn = QtGui.QPushButton(self.dockWidgetContents_2)
        self.abs_cor_btn.setObjectName(_fromUtf8("abs_cor_btn"))
        self.horizontalLayout_13.addWidget(self.abs_cor_btn)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.attentuation3D_check = QtGui.QCheckBox(self.dockWidgetContents_2)
        self.attentuation3D_check.setObjectName(_fromUtf8("attentuation3D_check"))
        self.horizontalLayout_14.addWidget(self.attentuation3D_check)
        self.att_cor_3D_btn = QtGui.QPushButton(self.dockWidgetContents_2)
        self.att_cor_3D_btn.setObjectName(_fromUtf8("att_cor_3D_btn"))
        self.horizontalLayout_14.addWidget(self.att_cor_3D_btn)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.About)
        QtCore.QObject.connect(self.sourceComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow.SelectNewSource)
        QtCore.QObject.connect(self.maxSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.MaxChanged)
        QtCore.QObject.connect(self.minSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.MinChanged)
        QtCore.QObject.connect(self.fit_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.FitRange)
        QtCore.QObject.connect(self.channel_radio, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.XTypeChanged)
        QtCore.QObject.connect(self.position_radio, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.XTypeChanged)
        QtCore.QObject.connect(self.angle_radio, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.XTypeChanged)
        QtCore.QObject.connect(self.dspacing_radio, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.XTypeChanged)
        QtCore.QObject.connect(self.dataset_spin, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.SelectData)
        QtCore.QObject.connect(self.prm_table, QtCore.SIGNAL(_fromUtf8("itemClicked(QTableWidgetItem*)")), MainWindow.ExportSelectionChanged)
        QtCore.QObject.connect(self.clear_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ClearData)
        QtCore.QObject.connect(self.outputComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow.SelectNewExport)
        QtCore.QObject.connect(self.maskLower_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), MainWindow.MaskEditChanged)
        QtCore.QObject.connect(self.maskLower_slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.MaskChanged)
        QtCore.QObject.connect(self.maskUpper_slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.MaskChanged)
        QtCore.QObject.connect(self.maskUpper_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), MainWindow.MaskEditChanged)
        QtCore.QObject.connect(self.prm_table, QtCore.SIGNAL(_fromUtf8("cellChanged(int,int)")), MainWindow.PostPrecChanged)
        QtCore.QObject.connect(self.postprocessGroupBox, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.PostProcessChanged)
        QtCore.QObject.connect(self.sam2det_edit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.SampleToDetectorChanged)
        QtCore.QObject.connect(self.wavelength_edit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.DSpacingChanged)
        QtCore.QObject.connect(self.stth_edit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.StthChanged)
        QtCore.QObject.connect(self.detDim_xmin_edit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.DetSizeChanged)
        QtCore.QObject.connect(self.detDim_xmax_edit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.DetSizeChanged)
        QtCore.QObject.connect(self.actionOpen, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.OpenScanman)
        QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.SaveScanman)
        QtCore.QObject.connect(self.geometry_check, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.GeomCorrChanged)
        QtCore.QObject.connect(self.flatfield_check, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.FlatFieldChanged)
        QtCore.QObject.connect(self.postprocessapplyButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.PostProcessApply)
        QtCore.QObject.connect(self.manparam_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ManparamPressed)
        QtCore.QObject.connect(self.selectall_check, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.SelectAllChanged)
        QtCore.QObject.connect(self.fitComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow.SelectNewFit)
        QtCore.QObject.connect(self.miscComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.SelectNewMisc)
        QtCore.QObject.connect(self.abs_cor_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.AbscorconfigurePressed)
        QtCore.QObject.connect(self.att_cor_3D_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.Attcor3DconfigurePressed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Scanman", None))
        self.label.setText(_translate("MainWindow", "Total datasets:", None))
        self.label_2.setText(_translate("MainWindow", "Display:", None))
        self.nrdatasets_label.setText(_translate("MainWindow", "0", None))
        self.cursource_label.setText(_translate("MainWindow", "----------", None))
        self.label_4.setText(_translate("MainWindow", "Source:", None))
        self.clear_btn.setText(_translate("MainWindow", "Clear", None))
        self.selectall_check.setText(_translate("MainWindow", "Select all", None))
        self.manparam_btn.setText(_translate("MainWindow", "Manipulate Parameters", None))
        self.prm_table.setSortingEnabled(False)
        item = self.prm_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Export", None))
        item = self.prm_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value", None))
        item = self.prm_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Post sets precision", None))
        self.postprocessGroupBox.setTitle(_translate("MainWindow", "Post process", None))
        self.label_9.setText(_translate("MainWindow", "Normalise:", None))
        self.label_10.setText(_translate("MainWindow", "Sum:", None))
        self.label_11.setText(_translate("MainWindow", "Scale:", None))
        self.scale_edit.setText(_translate("MainWindow", "1", None))
        self.label_13.setText(_translate("MainWindow", "stth offset", None))
        self.stthoffset_edit.setText(_translate("MainWindow", "0", None))
        self.justsum_check.setText(_translate("MainWindow", "Don\'t average overlap", None))
        self.postprocessapplyButton.setText(_translate("MainWindow", "Apply", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.source_tab), _translate("MainWindow", "Source", None))
        self.fitGroupBox.setTitle(_translate("MainWindow", "GroupBox", None))
        self.fit_btn.setText(_translate("MainWindow", "Fit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fit_tab), _translate("MainWindow", "Fit", None))
        self.outputGroupBox.setTitle(_translate("MainWindow", "GroupBox", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.output_tab), _translate("MainWindow", "Output", None))
        self.miscGroupBox.setTitle(_translate("MainWindow", "GroupBox", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.misc_tab), _translate("MainWindow", "Misc", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.dockWidget_4.setWindowTitle(_translate("MainWindow", "1D", None))
        self.maskUpper_label.setText(_translate("MainWindow", "Upper", None))
        self.maskLower_label.setText(_translate("MainWindow", "Lower", None))
        self.position_radio.setText(_translate("MainWindow", "Position (mm)", None))
        self.angle_radio.setText(_translate("MainWindow", "2θ Angle (°)", None))
        self.dspacing_radio.setText(_translate("MainWindow", "d-spacing (Å)", None))
        self.channel_radio.setText(_translate("MainWindow", "Channel", None))
        self.label_8.setText(_translate("MainWindow", "λ", None))
        self.wavelength_edit.setText(_translate("MainWindow", "1.659", None))
        self.label_5.setText(_translate("MainWindow", "stth", None))
        self.stth_edit.setText(_translate("MainWindow", "90", None))
        self.label_3.setText(_translate("MainWindow", "xmin", None))
        self.detDim_xmin_edit.setText(_translate("MainWindow", "-150", None))
        self.label_7.setText(_translate("MainWindow", "S2D", None))
        self.sam2det_edit.setText(_translate("MainWindow", "1000", None))
        self.label_6.setText(_translate("MainWindow", "xmax", None))
        self.detDim_xmax_edit.setText(_translate("MainWindow", "150", None))
        self.slideminLabel.setText(_translate("MainWindow", "Min", None))
        self.slidemaxLabel.setText(_translate("MainWindow", "Max", None))
        self.maxvalLabel.setText(_translate("MainWindow", "0", None))
        self.minvalLabel.setText(_translate("MainWindow", "0", None))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "2D", None))
        self.flatfield_check.setText(_translate("MainWindow", "Flat field correction", None))
        self.ffopen_button.setText(_translate("MainWindow", "Open", None))
        self.detectorsplit_label.setText(_translate("MainWindow", "Split detector vertically", None))
        self.vsplit_combo.setItemText(0, _translate("MainWindow", "1", None))
        self.vsplit_combo.setItemText(1, _translate("MainWindow", "2", None))
        self.vsplit_combo.setItemText(2, _translate("MainWindow", "3", None))
        self.vsplit_combo.setItemText(3, _translate("MainWindow", "4", None))
        self.vsplit_combo.setItemText(4, _translate("MainWindow", "5", None))
        self.geometry_check.setText(_translate("MainWindow", "Geometry correction", None))
        self.absorption_check.setText(_translate("MainWindow", "2D Attenuation correction", None))
        self.abs_cor_btn.setText(_translate("MainWindow", "Configure", None))
        self.attentuation3D_check.setText(_translate("MainWindow", "3D Attenuation correction", None))
        self.att_cor_3D_btn.setText(_translate("MainWindow", "Configure", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))

from matplotlibwidget import MatplotlibWidget
