# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fit\PeakGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Peak(object):
    def setupUi(self, Peak):
        Peak.setObjectName(_fromUtf8("Peak"))
        Peak.resize(382, 420)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Peak.sizePolicy().hasHeightForWidth())
        Peak.setSizePolicy(sizePolicy)
        Peak.setWindowOpacity(1.0)
        Peak.setTitle(_fromUtf8(""))
        self.verticalLayout_3 = QtGui.QVBoxLayout(Peak)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.range_tbl = QtGui.QTableWidget(Peak)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.range_tbl.sizePolicy().hasHeightForWidth())
        self.range_tbl.setSizePolicy(sizePolicy)
        self.range_tbl.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.range_tbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.range_tbl.setFrameShape(QtGui.QFrame.StyledPanel)
        self.range_tbl.setFrameShadow(QtGui.QFrame.Sunken)
        self.range_tbl.setProperty("showDropIndicator", False)
        self.range_tbl.setDragEnabled(False)
        self.range_tbl.setAlternatingRowColors(True)
        self.range_tbl.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.range_tbl.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.range_tbl.setTextElideMode(QtCore.Qt.ElideLeft)
        self.range_tbl.setObjectName(_fromUtf8("range_tbl"))
        self.range_tbl.setColumnCount(0)
        self.range_tbl.setRowCount(14)
        item = QtGui.QTableWidgetItem()
        self.range_tbl.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.range_tbl.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.range_tbl.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.range_tbl.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.range_tbl.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.range_tbl.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.range_tbl.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.range_tbl.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.range_tbl.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.range_tbl.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.range_tbl.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.range_tbl.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.range_tbl.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.range_tbl.setVerticalHeaderItem(13, item)
        self.range_tbl.horizontalHeader().setCascadingSectionResizes(False)
        self.range_tbl.horizontalHeader().setDefaultSectionSize(80)
        self.range_tbl.horizontalHeader().setHighlightSections(True)
        self.range_tbl.horizontalHeader().setMinimumSectionSize(19)
        self.range_tbl.horizontalHeader().setStretchLastSection(False)
        self.range_tbl.verticalHeader().setVisible(True)
        self.range_tbl.verticalHeader().setDefaultSectionSize(25)
        self.horizontalLayout.addWidget(self.range_tbl)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.addrange_btn = QtGui.QPushButton(Peak)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addrange_btn.sizePolicy().hasHeightForWidth())
        self.addrange_btn.setSizePolicy(sizePolicy)
        self.addrange_btn.setObjectName(_fromUtf8("addrange_btn"))
        self.verticalLayout_2.addWidget(self.addrange_btn)
        self.delrange_btn = QtGui.QPushButton(Peak)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delrange_btn.sizePolicy().hasHeightForWidth())
        self.delrange_btn.setSizePolicy(sizePolicy)
        self.delrange_btn.setObjectName(_fromUtf8("delrange_btn"))
        self.verticalLayout_2.addWidget(self.delrange_btn)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.background_box = QtGui.QGroupBox(Peak)
        self.background_box.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background_box.sizePolicy().hasHeightForWidth())
        self.background_box.setSizePolicy(sizePolicy)
        self.background_box.setCheckable(True)
        self.background_box.setChecked(False)
        self.background_box.setObjectName(_fromUtf8("background_box"))
        self.gridLayout = QtGui.QGridLayout(self.background_box)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bgsinglefixed_radio = QtGui.QRadioButton(self.background_box)
        self.bgsinglefixed_radio.setChecked(False)
        self.bgsinglefixed_radio.setObjectName(_fromUtf8("bgsinglefixed_radio"))
        self.gridLayout.addWidget(self.bgsinglefixed_radio, 1, 0, 1, 1)
        self.bgnonpeaks_radio = QtGui.QRadioButton(self.background_box)
        self.bgnonpeaks_radio.setChecked(True)
        self.bgnonpeaks_radio.setObjectName(_fromUtf8("bgnonpeaks_radio"))
        self.gridLayout.addWidget(self.bgnonpeaks_radio, 0, 0, 1, 1)
        self.bgallfixed_radio = QtGui.QRadioButton(self.background_box)
        self.bgallfixed_radio.setObjectName(_fromUtf8("bgallfixed_radio"))
        self.gridLayout.addWidget(self.bgallfixed_radio, 1, 1, 1, 1)
        self.bgfix_edit = QtGui.QLineEdit(self.background_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bgfix_edit.sizePolicy().hasHeightForWidth())
        self.bgfix_edit.setSizePolicy(sizePolicy)
        self.bgfix_edit.setMinimumSize(QtCore.QSize(10, 0))
        self.bgfix_edit.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.bgfix_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bgfix_edit.setObjectName(_fromUtf8("bgfix_edit"))
        self.gridLayout.addWidget(self.bgfix_edit, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.background_box)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.bgstart_edit = QtGui.QLineEdit(self.background_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bgstart_edit.sizePolicy().hasHeightForWidth())
        self.bgstart_edit.setSizePolicy(sizePolicy)
        self.bgstart_edit.setMinimumSize(QtCore.QSize(10, 0))
        self.bgstart_edit.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.bgstart_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bgstart_edit.setObjectName(_fromUtf8("bgstart_edit"))
        self.gridLayout.addWidget(self.bgstart_edit, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.background_box)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 4, 1, 1)
        self.bgend_edit = QtGui.QLineEdit(self.background_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bgend_edit.sizePolicy().hasHeightForWidth())
        self.bgend_edit.setSizePolicy(sizePolicy)
        self.bgend_edit.setMinimumSize(QtCore.QSize(10, 0))
        self.bgend_edit.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.bgend_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bgend_edit.setObjectName(_fromUtf8("bgend_edit"))
        self.gridLayout.addWidget(self.bgend_edit, 0, 5, 1, 1)
        self.bgrange_radio = QtGui.QRadioButton(self.background_box)
        self.bgrange_radio.setObjectName(_fromUtf8("bgrange_radio"))
        self.gridLayout.addWidget(self.bgrange_radio, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.background_box)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.varname_label = QtGui.QLabel(Peak)
        self.varname_label.setObjectName(_fromUtf8("varname_label"))
        self.horizontalLayout_2.addWidget(self.varname_label)
        self.var_slider = QtGui.QSlider(Peak)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.var_slider.sizePolicy().hasHeightForWidth())
        self.var_slider.setSizePolicy(sizePolicy)
        self.var_slider.setOrientation(QtCore.Qt.Horizontal)
        self.var_slider.setObjectName(_fromUtf8("var_slider"))
        self.horizontalLayout_2.addWidget(self.var_slider)
        self.varval_label = QtGui.QLabel(Peak)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.varval_label.sizePolicy().hasHeightForWidth())
        self.varval_label.setSizePolicy(sizePolicy)
        self.varval_label.setMinimumSize(QtCore.QSize(20, 0))
        self.varval_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.varval_label.setObjectName(_fromUtf8("varval_label"))
        self.horizontalLayout_2.addWidget(self.varval_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.setStretch(0, 20)
        self.verticalLayout_3.setStretch(2, 1)

        self.retranslateUi(Peak)
        QtCore.QObject.connect(self.delrange_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), Peak.DelRange)
        QtCore.QObject.connect(self.addrange_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), Peak.AddRange)
        QtCore.QObject.connect(self.range_tbl, QtCore.SIGNAL(_fromUtf8("cellChanged(int,int)")), Peak.CellValueChanged)
        QtCore.QObject.connect(self.range_tbl, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), Peak.UpdateUIValues)
        QtCore.QObject.connect(self.bgsinglefixed_radio, QtCore.SIGNAL(_fromUtf8("clicked()")), Peak.BgChanged)
        QtCore.QObject.connect(self.bgnonpeaks_radio, QtCore.SIGNAL(_fromUtf8("clicked()")), Peak.BgChanged)
        QtCore.QObject.connect(self.bgallfixed_radio, QtCore.SIGNAL(_fromUtf8("clicked()")), Peak.BgChanged)
        QtCore.QObject.connect(self.background_box, QtCore.SIGNAL(_fromUtf8("clicked()")), Peak.BgChanged)
        QtCore.QObject.connect(self.bgrange_radio, QtCore.SIGNAL(_fromUtf8("clicked()")), Peak.BgChanged)
        QtCore.QObject.connect(self.var_slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Peak.VarSliderValChanged)
        QtCore.QObject.connect(self.bgstart_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Peak.BgChanged)
        QtCore.QObject.connect(self.bgend_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Peak.BgChanged)
        QtCore.QObject.connect(self.bgfix_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Peak.BgChanged)
        QtCore.QMetaObject.connectSlotsByName(Peak)

    def retranslateUi(self, Peak):
        Peak.setWindowTitle(_translate("Peak", "Peak", None))
        self.range_tbl.setSortingEnabled(False)
        item = self.range_tbl.verticalHeaderItem(0)
        item.setText(_translate("Peak", "Range_start", None))
        item = self.range_tbl.verticalHeaderItem(1)
        item.setText(_translate("Peak", "Range_end", None))
        item = self.range_tbl.verticalHeaderItem(2)
        item.setText(_translate("Peak", "Position", None))
        item = self.range_tbl.verticalHeaderItem(3)
        item.setText(_translate("Peak", "FWHM", None))
        item = self.range_tbl.verticalHeaderItem(4)
        item.setText(_translate("Peak", "Intensity", None))
        item = self.range_tbl.verticalHeaderItem(5)
        item.setText(_translate("Peak", "Background", None))
        item = self.range_tbl.verticalHeaderItem(6)
        item.setText(_translate("Peak", "Chi^2", None))
        item = self.range_tbl.verticalHeaderItem(7)
        item.setText(_translate("Peak", "R^2", None))
        item = self.range_tbl.verticalHeaderItem(8)
        item.setText(_translate("Peak", "nIter", None))
        item = self.range_tbl.verticalHeaderItem(9)
        item.setText(_translate("Peak", "Time", None))
        item = self.range_tbl.verticalHeaderItem(10)
        item.setText(_translate("Peak", "Intensity_sum", None))
        item = self.range_tbl.verticalHeaderItem(11)
        item.setText(_translate("Peak", "Intensity_area", None))
        item = self.range_tbl.verticalHeaderItem(12)
        item.setText(_translate("Peak", "Counts", None))
        item = self.range_tbl.verticalHeaderItem(13)
        item.setText(_translate("Peak", "Err_µɛ", None))
        self.addrange_btn.setText(_translate("Peak", "Add", None))
        self.delrange_btn.setText(_translate("Peak", "Del", None))
        self.background_box.setTitle(_translate("Peak", "Background", None))
        self.bgsinglefixed_radio.setText(_translate("Peak", "Single fixed", None))
        self.bgnonpeaks_radio.setText(_translate("Peak", "Non-peaks", None))
        self.bgallfixed_radio.setText(_translate("Peak", "All fixed:", None))
        self.bgfix_edit.setText(_translate("Peak", "0", None))
        self.label_4.setText(_translate("Peak", "bg_start:", None))
        self.bgstart_edit.setText(_translate("Peak", "0", None))
        self.label_5.setText(_translate("Peak", "bg_end:", None))
        self.bgend_edit.setText(_translate("Peak", "0", None))
        self.bgrange_radio.setText(_translate("Peak", "Fixed range -->", None))
        self.varname_label.setText(_translate("Peak", "FitVarName", None))
        self.varval_label.setText(_translate("Peak", "0", None))

