# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Source\GenPeaksGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GenPeaks(object):
    def setupUi(self, GenPeaks):
        GenPeaks.setObjectName(_fromUtf8("GenPeaks"))
        GenPeaks.resize(332, 286)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GenPeaks.sizePolicy().hasHeightForWidth())
        GenPeaks.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtGui.QVBoxLayout(GenPeaks)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_16 = QtGui.QLabel(GenPeaks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 0, 6, 1, 1)
        self.nchannels_edit = QtGui.QLineEdit(GenPeaks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nchannels_edit.sizePolicy().hasHeightForWidth())
        self.nchannels_edit.setSizePolicy(sizePolicy)
        self.nchannels_edit.setMinimumSize(QtCore.QSize(10, 0))
        self.nchannels_edit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nchannels_edit.setInputMask(_fromUtf8(""))
        self.nchannels_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nchannels_edit.setObjectName(_fromUtf8("nchannels_edit"))
        self.gridLayout.addWidget(self.nchannels_edit, 0, 1, 1, 1)
        self.background_edit = QtGui.QLineEdit(GenPeaks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background_edit.sizePolicy().hasHeightForWidth())
        self.background_edit.setSizePolicy(sizePolicy)
        self.background_edit.setMinimumSize(QtCore.QSize(10, 0))
        self.background_edit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.background_edit.setInputMask(_fromUtf8(""))
        self.background_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.background_edit.setObjectName(_fromUtf8("background_edit"))
        self.gridLayout.addWidget(self.background_edit, 0, 4, 1, 1)
        self.label_14 = QtGui.QLabel(GenPeaks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(GenPeaks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.noise_edit = QtGui.QLineEdit(GenPeaks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noise_edit.sizePolicy().hasHeightForWidth())
        self.noise_edit.setSizePolicy(sizePolicy)
        self.noise_edit.setMinimumSize(QtCore.QSize(10, 0))
        self.noise_edit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.noise_edit.setInputMask(_fromUtf8(""))
        self.noise_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.noise_edit.setObjectName(_fromUtf8("noise_edit"))
        self.gridLayout.addWidget(self.noise_edit, 0, 7, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.peaks_tbl = QtGui.QTableWidget(GenPeaks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peaks_tbl.sizePolicy().hasHeightForWidth())
        self.peaks_tbl.setSizePolicy(sizePolicy)
        self.peaks_tbl.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.peaks_tbl.setAcceptDrops(True)
        self.peaks_tbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.peaks_tbl.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.peaks_tbl.setAlternatingRowColors(True)
        self.peaks_tbl.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.peaks_tbl.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.peaks_tbl.setObjectName(_fromUtf8("peaks_tbl"))
        self.peaks_tbl.setColumnCount(3)
        self.peaks_tbl.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.peaks_tbl.setItem(2, 2, item)
        self.peaks_tbl.horizontalHeader().setCascadingSectionResizes(False)
        self.peaks_tbl.horizontalHeader().setDefaultSectionSize(70)
        self.peaks_tbl.horizontalHeader().setHighlightSections(True)
        self.peaks_tbl.horizontalHeader().setMinimumSectionSize(19)
        self.peaks_tbl.horizontalHeader().setStretchLastSection(False)
        self.peaks_tbl.verticalHeader().setVisible(True)
        self.horizontalLayout.addWidget(self.peaks_tbl)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.addpeak_btn = QtGui.QPushButton(GenPeaks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addpeak_btn.sizePolicy().hasHeightForWidth())
        self.addpeak_btn.setSizePolicy(sizePolicy)
        self.addpeak_btn.setObjectName(_fromUtf8("addpeak_btn"))
        self.verticalLayout_2.addWidget(self.addpeak_btn)
        self.delpeak_btn = QtGui.QPushButton(GenPeaks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delpeak_btn.sizePolicy().hasHeightForWidth())
        self.delpeak_btn.setSizePolicy(sizePolicy)
        self.delpeak_btn.setObjectName(_fromUtf8("delpeak_btn"))
        self.verticalLayout_2.addWidget(self.delpeak_btn)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.create_btn = QtGui.QPushButton(GenPeaks)
        self.create_btn.setObjectName(_fromUtf8("create_btn"))
        self.verticalLayout_3.addWidget(self.create_btn)

        self.retranslateUi(GenPeaks)
        QtCore.QObject.connect(self.delpeak_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), GenPeaks.DelPeak)
        QtCore.QObject.connect(self.addpeak_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), GenPeaks.AddPeak)
        QtCore.QObject.connect(self.create_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), GenPeaks.GetData)
        QtCore.QMetaObject.connectSlotsByName(GenPeaks)

    def retranslateUi(self, GenPeaks):
        GenPeaks.setWindowTitle(_translate("GenPeaks", "GenPeaks", None))
        GenPeaks.setTitle(_translate("GenPeaks", "GenPeaks", None))
        self.label_16.setText(_translate("GenPeaks", "noise", None))
        self.nchannels_edit.setText(_translate("GenPeaks", "400", None))
        self.background_edit.setText(_translate("GenPeaks", "2", None))
        self.label_14.setText(_translate("GenPeaks", "Nr Channels", None))
        self.label_15.setText(_translate("GenPeaks", "background", None))
        self.noise_edit.setText(_translate("GenPeaks", "2", None))
        self.peaks_tbl.setSortingEnabled(True)
        item = self.peaks_tbl.verticalHeaderItem(0)
        item.setText(_translate("GenPeaks", "1", None))
        item = self.peaks_tbl.verticalHeaderItem(1)
        item.setText(_translate("GenPeaks", "2", None))
        item = self.peaks_tbl.verticalHeaderItem(2)
        item.setText(_translate("GenPeaks", "3", None))
        item = self.peaks_tbl.horizontalHeaderItem(0)
        item.setText(_translate("GenPeaks", "Center", None))
        item = self.peaks_tbl.horizontalHeaderItem(1)
        item.setText(_translate("GenPeaks", "Width", None))
        item = self.peaks_tbl.horizontalHeaderItem(2)
        item.setText(_translate("GenPeaks", "Amplitude", None))
        __sortingEnabled = self.peaks_tbl.isSortingEnabled()
        self.peaks_tbl.setSortingEnabled(False)
        item = self.peaks_tbl.item(0, 0)
        item.setText(_translate("GenPeaks", "200", None))
        item = self.peaks_tbl.item(0, 1)
        item.setText(_translate("GenPeaks", "40", None))
        item = self.peaks_tbl.item(0, 2)
        item.setText(_translate("GenPeaks", "10", None))
        item = self.peaks_tbl.item(1, 0)
        item.setText(_translate("GenPeaks", "300", None))
        item = self.peaks_tbl.item(1, 1)
        item.setText(_translate("GenPeaks", "10", None))
        item = self.peaks_tbl.item(1, 2)
        item.setText(_translate("GenPeaks", "3", None))
        item = self.peaks_tbl.item(2, 0)
        item.setText(_translate("GenPeaks", "60", None))
        item = self.peaks_tbl.item(2, 1)
        item.setText(_translate("GenPeaks", "20", None))
        item = self.peaks_tbl.item(2, 2)
        item.setText(_translate("GenPeaks", "7", None))
        self.peaks_tbl.setSortingEnabled(__sortingEnabled)
        self.addpeak_btn.setText(_translate("GenPeaks", "Add peak", None))
        self.delpeak_btn.setText(_translate("GenPeaks", "Del peak", None))
        self.create_btn.setText(_translate("GenPeaks", "Create", None))

