# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Source\ScanmanPeakFit_pkfGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ScanmanPeakFit_pkf(object):
    def setupUi(self, ScanmanPeakFit_pkf):
        ScanmanPeakFit_pkf.setObjectName(_fromUtf8("ScanmanPeakFit_pkf"))
        ScanmanPeakFit_pkf.resize(400, 300)
        self.verticalLayout = QtGui.QVBoxLayout(ScanmanPeakFit_pkf)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.params_check = QtGui.QCheckBox(ScanmanPeakFit_pkf)
        self.params_check.setChecked(True)
        self.params_check.setObjectName(_fromUtf8("params_check"))
        self.horizontalLayout_2.addWidget(self.params_check)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.permutate_check = QtGui.QCheckBox(ScanmanPeakFit_pkf)
        self.permutate_check.setObjectName(_fromUtf8("permutate_check"))
        self.horizontalLayout_2.addWidget(self.permutate_check)
        self.label_2 = QtGui.QLabel(ScanmanPeakFit_pkf)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.precision_edit = QtGui.QLineEdit(ScanmanPeakFit_pkf)
        self.precision_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.precision_edit.setObjectName(_fromUtf8("precision_edit"))
        self.horizontalLayout_2.addWidget(self.precision_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.prm_table = QtGui.QTableWidget(ScanmanPeakFit_pkf)
        self.prm_table.setObjectName(_fromUtf8("prm_table"))
        self.prm_table.setColumnCount(2)
        self.prm_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.prm_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.prm_table.setHorizontalHeaderItem(1, item)
        self.prm_table.horizontalHeader().setCascadingSectionResizes(False)
        self.prm_table.horizontalHeader().setStretchLastSection(True)
        self.prm_table.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_2.addWidget(self.prm_table)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.peaks_check = QtGui.QCheckBox(ScanmanPeakFit_pkf)
        self.peaks_check.setChecked(True)
        self.peaks_check.setObjectName(_fromUtf8("peaks_check"))
        self.horizontalLayout_4.addWidget(self.peaks_check)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.peak_table = QtGui.QTableWidget(ScanmanPeakFit_pkf)
        self.peak_table.setObjectName(_fromUtf8("peak_table"))
        self.peak_table.setColumnCount(1)
        self.peak_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.peak_table.setHorizontalHeaderItem(0, item)
        self.peak_table.horizontalHeader().setCascadingSectionResizes(False)
        self.peak_table.horizontalHeader().setStretchLastSection(True)
        self.peak_table.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_3.addWidget(self.peak_table)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(ScanmanPeakFit_pkf)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.datavals_combo = QtGui.QComboBox(ScanmanPeakFit_pkf)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datavals_combo.sizePolicy().hasHeightForWidth())
        self.datavals_combo.setSizePolicy(sizePolicy)
        self.datavals_combo.setObjectName(_fromUtf8("datavals_combo"))
        self.horizontalLayout.addWidget(self.datavals_combo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ok_btn = QtGui.QPushButton(ScanmanPeakFit_pkf)
        self.ok_btn.setObjectName(_fromUtf8("ok_btn"))
        self.horizontalLayout_5.addWidget(self.ok_btn)
        self.cancel_btn = QtGui.QPushButton(ScanmanPeakFit_pkf)
        self.cancel_btn.setObjectName(_fromUtf8("cancel_btn"))
        self.horizontalLayout_5.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(ScanmanPeakFit_pkf)
        QtCore.QObject.connect(self.ok_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), ScanmanPeakFit_pkf.ok_pressed)
        QtCore.QObject.connect(self.prm_table, QtCore.SIGNAL(_fromUtf8("itemChanged(QTableWidgetItem*)")), ScanmanPeakFit_pkf.ParamSelectionChanged)
        QtCore.QObject.connect(self.peak_table, QtCore.SIGNAL(_fromUtf8("itemChanged(QTableWidgetItem*)")), ScanmanPeakFit_pkf.PeakSelectionChanged)
        QtCore.QObject.connect(self.peaks_check, QtCore.SIGNAL(_fromUtf8("clicked()")), ScanmanPeakFit_pkf.Selectallpeaks_pressed)
        QtCore.QObject.connect(self.params_check, QtCore.SIGNAL(_fromUtf8("clicked()")), ScanmanPeakFit_pkf.Selectallparams_pressed)
        QtCore.QObject.connect(self.cancel_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), ScanmanPeakFit_pkf.close_pressed)
        QtCore.QMetaObject.connectSlotsByName(ScanmanPeakFit_pkf)

    def retranslateUi(self, ScanmanPeakFit_pkf):
        ScanmanPeakFit_pkf.setWindowTitle(_translate("ScanmanPeakFit_pkf", "Peakfit source", None))
        self.params_check.setText(_translate("ScanmanPeakFit_pkf", "Select all", None))
        self.permutate_check.setText(_translate("ScanmanPeakFit_pkf", "Permutate", None))
        self.label_2.setText(_translate("ScanmanPeakFit_pkf", "Precision", None))
        self.precision_edit.setText(_translate("ScanmanPeakFit_pkf", "0.05", None))
        item = self.prm_table.horizontalHeaderItem(0)
        item.setText(_translate("ScanmanPeakFit_pkf", "Variable param", None))
        item = self.prm_table.horizontalHeaderItem(1)
        item.setText(_translate("ScanmanPeakFit_pkf", "Precision", None))
        self.peaks_check.setText(_translate("ScanmanPeakFit_pkf", "Select all", None))
        item = self.peak_table.horizontalHeaderItem(0)
        item.setText(_translate("ScanmanPeakFit_pkf", "Peak", None))
        self.label.setText(_translate("ScanmanPeakFit_pkf", "Data values:", None))
        self.ok_btn.setText(_translate("ScanmanPeakFit_pkf", "OK", None))
        self.cancel_btn.setText(_translate("ScanmanPeakFit_pkf", "Cancel", None))

